[tox]
requires =
    tox >= 4.20
envlist = cap,dev,bmap,emmc,sdmmc,qspi,deploy,clean
skip_missing_interpreters = true
isolated_build = true
skipsdist = true

[base]
deps =
    pip>=22.1

[testenv]
skip_install = true
install_command = pip install {opts} {packages}

[testenv:{cap,dev,bmap,emmc,sdmmc,qemu,qspi,deploy}]
envdir = {toxinidir}/.venv
# these tox env cmds share a virtual env using the following plugin
# https://github.com/masenf/tox-ignore-env-name-mismatch as toxfile.py
runner = ignore_env_name_mismatch
always_copy = True

allowlist_externals =
    bash

description =
    cap: Create a kas build virtual environment with managed deps and capabilities (requires sudo)
    dev: Create a kas build virtual environment with managed deps (no special privs)
    emmc: Build the (wic) emmc boot target
    sdmmc: Build the default (wic) sdmmc boot target
    bmap: Burn the sdmmc wic image to sdcard device (default: {env:DISK})
    qspi: Clean and build the qspi boot target
    deploy: Deploy qspi build products to sdcard
    qemu: Populate a qemuarm machine build tree (default: qemuarm)

setenv =
    IPP = {env:IPP:}
    DEBUG = {env:DEBUG:}
    DISK = {env:DISK:/dev/mmcblk0}
    IMAGE = {env:IMAGE:devel-image-minimal}
    UBOOT_CONFIG = {env:UBOOT_CONFIG:{envname}}
    KAS_MACHINE = {env:KAS_MACHINE:me-aa1-270-2i2-d11e-nfx3}
    DEPLOY_DIR = {env:DEPLOY_DIR:build/tmp-glibc/deploy/images/{env:KAS_MACHINE}}

passenv =
    DISPLAY
    XAUTHORITY
    GID
    UID
    HOME
    USERNAME
    USER
    CI
    LANG
    LC_COLLATE
    SSH_*
    XDG_*
    PYTHONIOENCODING
    PIP_DOWNLOAD_CACHE

deps =
    # logging_tree
    {[base]deps}
    kas
    bmaptool @ git+https://github.com/sarnold/bmap-tools.git@v3.9.0.1#egg=bmaptool
    pyserv @ git+https://github.com/sarnold/pyserv.git@1.9.1#egg=pyserv

commands_pre =
    bash -c '[[ -e layers/meta-user-aa1 ]] || ( mkdir -p layers && git clone https://github.com/VCTLabs/meta-user-aa1.git -b oe-mickledore layers/meta-user-aa1 )'

commands =
    {cap,dev}: kas checkout layers/meta-user-aa1/kas/{posargs:"systemd"}.yaml:layers/meta-user-aa1/kas/site.yaml
    qspi: bash -c 'rm -rf build/tmp*'
    {qspi,sdmmc,emmc}: kas shell layers/meta-user-aa1/kas/{posargs:"systemd"}.yaml:layers/meta-user-aa1/kas/site.yaml -c 'PACKAGE_FEED_IP_PORT={env:IPP} UBOOT_CONFIG={env:UBOOT_CONFIG} bitbake {env:IMAGE}'
    qemu: kas shell layers/meta-user-aa1/kas/{posargs:"qemuarm"}.yaml:layers/meta-user-aa1/kas/site.yaml -c 'bitbake {env:IMAGE}'
    bmap: bmaptool copy {env:DEPLOY_DIR}{/}{env:IMAGE}-{env:KAS_MACHINE}.wic {env:DISK}
    deploy: bash scripts/populate_sdcard.sh {env:DISK} {env:DEPLOY_DIR}

commands_post =
    cap: bash -c 'sudo setcap cap_net_bind_service+ep {envpython}'
    cap: bash -c 'sudo setcap cap_net_bind_service+ep {envpython}3'

[testenv:lint]
skip_install = true
always_copy = False

allowlist_externals =
    bash

deps =
    {[base]deps}
    kas
    reuse

commands =
    reuse lint

[testenv:changes]
skip_install = true
always_copy = False

allowlist_externals =
    bash

deps =
    {[base]deps}
    gitchangelog @ https://github.com/sarnold/gitchangelog/releases/download/3.2.0/gitchangelog-3.2.0-py3-none-any.whl

commands =
    bash -c 'gitchangelog {posargs} > CHANGELOG.rst'

[testenv:clean]
skip_install = true
allowlist_externals =
    bash

deps =
    pip>=21.1

commands =
    bash -c 'rm -rf  __pycache__ qspi/ build/tmp*'
